- hosts:
    - app_servers
  become: yes
  roles:
    - { role: app_server, tags: [ django ] }
  tags:
    - app


- hosts: db_servers
  become: yes
  roles:
    - role: Ansibles.postgresql
      postgresql_version: 9.5
      postgresql_databases:
        - name: "{{ DB_NAME }}"
      postgresql_users:
        - name: "{{ DB_USER }}"
          pass: "{{ DB_PASSWORD }}"
      postgresql_user_privileges:
        - name: "{{ DB_USER }}"
          db: "{{ DB_NAME }}"
          priv: ALL
      tags:
        - db_server

  tasks:
    - name: Allow DB user to create DBs for tests
      postgresql_user: name={{ DB_USER }} role_attr_flags=CREATEDB

- hosts: app_servers
  gather_facts: yes
  become: no

  tasks:
    - name: Export DJANGO_SETTINGS_MODULE via bashrc in development
      lineinfile:
        dest: "/home/{{ ansible_ssh_user  }}/.bashrc"
        state: present
        line: "export DJANGO_SETTINGS_MODULE={{ SETTINGS_DIR }}.settings.{{ APP_ENVIRONMENT }}"
      when: APP_ENVIRONMENT == "development"
