---
APP_NAME: app
SETTINGS_DIR: configuration
APP_USER: "{{ ansible_ssh_user }}"
APP_HOME: "/home/{{ APP_USER }}"
APP_DIR: "{{ APP_HOME }}/{{ APP_NAME }}"
APP_VIRTUALENV: "{{ APP_HOME }}/.virtualenvs/{{ APP_NAME }}"
APP_PORT: 8000
APP_PORT_HTTPS: 443

DB_NAME: "{{ APP_NAME }}"
DB_USER: "{{ APP_NAME }}"
DB_PASSWORD: secretpassword

BROKER: amqp://guest:guest@localhost:5672//
BROKER_API: http://guest:guest@localhost:15672/api

APP_SERVER_TO_MONITOR: 10.0.0.5

APP_SERVER: app_servers